//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fingerprints.LocalResource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Fingerprints.LocalResource.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Absent.
        /// </summary>
        public static string Absent {
            get {
                return ResourceManager.GetString("Absent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        public static string Action {
            get {
                return ResourceManager.GetString("Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity Date.
        /// </summary>
        public static string Activity_Date {
            get {
                return ResourceManager.GetString("Activity_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity Notes.
        /// </summary>
        public static string Activity_Notes {
            get {
                return ResourceManager.GetString("Activity_Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address Change.
        /// </summary>
        public static string Address_Change {
            get {
                return ResourceManager.GetString("Address_Change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age.
        /// </summary>
        public static string Age {
            get {
                return ResourceManager.GetString("Age", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alert.
        /// </summary>
        public static string Alert {
            get {
                return ResourceManager.GetString("Alert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Rights Reserved.
        /// </summary>
        public static string All_Rights_Reserved {
            get {
                return ResourceManager.GetString("All_Rights_Reserved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Link Inc.
        /// </summary>
        public static string Application_Link_Inc {
            get {
                return ResourceManager.GetString("Application_Link_Inc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arrival Time.
        /// </summary>
        public static string Arrival_Time {
            get {
                return ResourceManager.GetString("Arrival_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing Attachments.
        /// </summary>
        public static string Billing_Attachments {
            get {
                return ResourceManager.GetString("Billing_Attachments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BMI Vs Age.
        /// </summary>
        public static string BMI_Vs_Age {
            get {
                return ResourceManager.GetString("BMI_Vs_Age", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Center Overview.
        /// </summary>
        public static string CenterOverview {
            get {
                return ResourceManager.GetString("CenterOverview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Address.
        /// </summary>
        public static string Change_Address {
            get {
                return ResourceManager.GetString("Change_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Status.
        /// </summary>
        public static string Change_Status {
            get {
                return ResourceManager.GetString("Change_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Child Growth Chart.
        /// </summary>
        public static string Child_Growth_Chart {
            get {
                return ResourceManager.GetString("Child_Growth_Chart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Child has poor attendance.
        /// </summary>
        public static string Child_has_poor_attendance {
            get {
                return ResourceManager.GetString("Child_has_poor_attendance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Child has very great attendance.
        /// </summary>
        public static string Child_has_very_great_attendance {
            get {
                return ResourceManager.GetString("Child_has_very_great_attendance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Child Length.
        /// </summary>
        public static string Child_Length {
            get {
                return ResourceManager.GetString("Child_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Child Name.
        /// </summary>
        public static string Child_Name {
            get {
                return ResourceManager.GetString("Child_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Child Weight.
        /// </summary>
        public static string Child_Weight {
            get {
                return ResourceManager.GetString("Child_Weight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Child Development Center of America.
        /// </summary>
        public static string ChildDevelopmentCenterofAmerica {
            get {
                return ResourceManager.GetString("ChildDevelopmentCenterofAmerica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Child Length.
        /// </summary>
        public static string ChildLength {
            get {
                return ResourceManager.GetString("ChildLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Reason.
        /// </summary>
        public static string Choose_Reason {
            get {
                return ResourceManager.GetString("Choose_Reason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classes at.
        /// </summary>
        public static string Classes_at {
            get {
                return ResourceManager.GetString("Classes_at", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here for Parent Engagement Request.
        /// </summary>
        public static string Click_here_for_Parent_Engagement_Request {
            get {
                return ResourceManager.GetString("Click_here_for_Parent_Engagement_Request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to Mark Absent.
        /// </summary>
        public static string Click_here_to_Mark_Absent {
            get {
                return ResourceManager.GetString("Click_here_to_Mark_Absent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to Mark Late Arrival.
        /// </summary>
        public static string Click_here_to_Mark_Late_Arrival {
            get {
                return ResourceManager.GetString("Click_here_to_Mark_Late_Arrival", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to see growth chart details.
        /// </summary>
        public static string Click_here_to_see_growth_chart_details {
            get {
                return ResourceManager.GetString("Click_here_to_see_growth_chart_details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to see screen details.
        /// </summary>
        public static string Click_here_to_see_screen_details {
            get {
                return ResourceManager.GetString("Click_here_to_see_screen_details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to closed today.
        /// </summary>
        public static string closed_today {
            get {
                return ResourceManager.GetString("closed_today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright.
        /// </summary>
        public static string Copyright {
            get {
                return ResourceManager.GetString("Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Education Status Is.
        /// </summary>
        public static string Current_Education_Status_Is {
            get {
                return ResourceManager.GetString("Current_Education_Status_Is", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Employment Status Is.
        /// </summary>
        public static string Current_Employment_Status_Is {
            get {
                return ResourceManager.GetString("Current_Employment_Status_Is", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Military Status Is.
        /// </summary>
        public static string Current_Military_Status_Is {
            get {
                return ResourceManager.GetString("Current_Military_Status_Is", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of Change.
        /// </summary>
        public static string Date_of_Change {
            get {
                return ResourceManager.GetString("Date_of_Change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day of Volunteer.
        /// </summary>
        public static string Day_of_Volunteer {
            get {
                return ResourceManager.GetString("Day_of_Volunteer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Education Status.
        /// </summary>
        public static string Education_Status {
            get {
                return ResourceManager.GetString("Education_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employment Status.
        /// </summary>
        public static string Employment_Status {
            get {
                return ResourceManager.GetString("Employment_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Events.
        /// </summary>
        public static string Events {
            get {
                return ResourceManager.GetString("Events", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Events registered on other center.
        /// </summary>
        public static string Events_registered_on_other_center {
            get {
                return ResourceManager.GetString("Events_registered_on_other_center", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Events registered on your center.
        /// </summary>
        public static string Events_registered_on_your_center {
            get {
                return ResourceManager.GetString("Events_registered_on_your_center", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected Arrival Time.
        /// </summary>
        public static string Expected_Arrival_Time {
            get {
                return ResourceManager.GetString("Expected_Arrival_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export All.
        /// </summary>
        public static string Export_All {
            get {
                return ResourceManager.GetString("Export_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export PDF.
        /// </summary>
        public static string Export_PDF {
            get {
                return ResourceManager.GetString("Export_PDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Family Access Portal.
        /// </summary>
        public static string Family_Access_Portal {
            get {
                return ResourceManager.GetString("Family_Access_Portal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Family Service Worker.
        /// </summary>
        public static string Family_Service_Worker {
            get {
                return ResourceManager.GetString("Family_Service_Worker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Growth Chart of.
        /// </summary>
        public static string GrowthChartof {
            get {
                return ResourceManager.GetString("GrowthChartof", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Happy BirthDay.
        /// </summary>
        public static string Happy_Birthday {
            get {
                return ResourceManager.GetString("Happy_Birthday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HeadCircu..
        /// </summary>
        public static string HeadCircu {
            get {
                return ResourceManager.GetString("HeadCircu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Head Circumference vs Age.
        /// </summary>
        public static string HeadCircumferencevsAge {
            get {
                return ResourceManager.GetString("HeadCircumferencevsAge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Health.
        /// </summary>
        public static string Health {
            get {
                return ResourceManager.GetString("Health", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Homeless Status.
        /// </summary>
        public static string Homeless_Status {
            get {
                return ResourceManager.GetString("Homeless_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hours.
        /// </summary>
        public static string Hours {
            get {
                return ResourceManager.GetString("Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hours of Volunteer.
        /// </summary>
        public static string Hours_of_Volunteer {
            get {
                return ResourceManager.GetString("Hours_of_Volunteer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I would like to volunteer.
        /// </summary>
        public static string I_would_like_to_volunteer {
            get {
                return ResourceManager.GetString("I_would_like_to_volunteer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inch.
        /// </summary>
        public static string Inch {
            get {
                return ResourceManager.GetString("Inch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insurance Status.
        /// </summary>
        public static string Insurance_Status {
            get {
                return ResourceManager.GetString("Insurance_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length.
        /// </summary>
        public static string Length {
            get {
                return ResourceManager.GetString("Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length(CM).
        /// </summary>
        public static string LengthofCM {
            get {
                return ResourceManager.GetString("LengthofCM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length(Inch).
        /// </summary>
        public static string LengthofInch {
            get {
                return ResourceManager.GetString("LengthofInch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length vs Age.
        /// </summary>
        public static string LengthvsAge {
            get {
                return ResourceManager.GetString("LengthvsAge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark Absent.
        /// </summary>
        public static string Mark_Absent {
            get {
                return ResourceManager.GetString("Mark_Absent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark Late.
        /// </summary>
        public static string Mark_Late {
            get {
                return ResourceManager.GetString("Mark_Late", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark Late Arrival.
        /// </summary>
        public static string Mark_Late_Arrival {
            get {
                return ResourceManager.GetString("Mark_Late_Arrival", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark Late Arrival For.
        /// </summary>
        public static string Mark_Late_Arrival_For {
            get {
                return ResourceManager.GetString("Mark_Late_Arrival_For", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Military Status.
        /// </summary>
        public static string Military_Status {
            get {
                return ResourceManager.GetString("Military_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minutes.
        /// </summary>
        public static string Minutes {
            get {
                return ResourceManager.GetString("Minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month.
        /// </summary>
        public static string Month {
            get {
                return ResourceManager.GetString("Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Events Available For This Center.
        /// </summary>
        public static string No_Events_Available_For_This_Center {
            get {
                return ResourceManager.GetString("No_Events_Available_For_This_Center", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        public static string Notes {
            get {
                return ResourceManager.GetString("Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nurse.
        /// </summary>
        public static string Nurse {
            get {
                return ResourceManager.GetString("Nurse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Centers.
        /// </summary>
        public static string Other_Centers {
            get {
                return ResourceManager.GetString("Other_Centers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent Engagement.
        /// </summary>
        public static string Parent_Engagement {
            get {
                return ResourceManager.GetString("Parent_Engagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent Participation.
        /// </summary>
        public static string Parent_Participation {
            get {
                return ResourceManager.GetString("Parent_Participation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please complete the following survey.
        /// </summary>
        public static string Please_complete_the_following_survey {
            get {
                return ResourceManager.GetString("Please_complete_the_following_survey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Wait.
        /// </summary>
        public static string Please_Wait {
            get {
                return ResourceManager.GetString("Please_Wait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pound.
        /// </summary>
        public static string Pound {
            get {
                return ResourceManager.GetString("Pound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading.
        /// </summary>
        public static string Reading {
            get {
                return ResourceManager.GetString("Reading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reason.
        /// </summary>
        public static string Reason {
            get {
                return ResourceManager.GetString("Reason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registered.
        /// </summary>
        public static string Registered {
            get {
                return ResourceManager.GetString("Registered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registered Events.
        /// </summary>
        public static string Registered_Events {
            get {
                return ResourceManager.GetString("Registered_Events", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to School Calendar.
        /// </summary>
        public static string School_Calendar {
            get {
                return ResourceManager.GetString("School_Calendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screening Results.
        /// </summary>
        public static string Screening_Results {
            get {
                return ResourceManager.GetString("Screening_Results", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select All.
        /// </summary>
        public static string Select_all {
            get {
                return ResourceManager.GetString("Select_all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Child(s).
        /// </summary>
        public static string Select_Child_s {
            get {
                return ResourceManager.GetString("Select_Child_s", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        public static string State {
            get {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status Change Notes.
        /// </summary>
        public static string Status_Change_Notes {
            get {
                return ResourceManager.GetString("Status_Change_Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teacher.
        /// </summary>
        public static string Teacher {
            get {
                return ResourceManager.GetString("Teacher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upcoming Events.
        /// </summary>
        public static string Upcoming_Events {
            get {
                return ResourceManager.GetString("Upcoming_Events", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volunteer.
        /// </summary>
        public static string Volunteer {
            get {
                return ResourceManager.GetString("Volunteer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight.
        /// </summary>
        public static string Weight {
            get {
                return ResourceManager.GetString("Weight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight(kg).
        /// </summary>
        public static string Weight_Kg {
            get {
                return ResourceManager.GetString("Weight_Kg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight(Pound).
        /// </summary>
        public static string Weight_Pound {
            get {
                return ResourceManager.GetString("Weight_Pound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight vs Age.
        /// </summary>
        public static string WeightvsAge {
            get {
                return ResourceManager.GetString("WeightvsAge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight vs Length.
        /// </summary>
        public static string WeightvsLength {
            get {
                return ResourceManager.GetString("WeightvsLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Writing.
        /// </summary>
        public static string Writing {
            get {
                return ResourceManager.GetString("Writing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Center Name.
        /// </summary>
        public static string Your_Center_Name {
            get {
                return ResourceManager.GetString("Your_Center_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Current Address Is.
        /// </summary>
        public static string Your_Current_Address_Is {
            get {
                return ResourceManager.GetString("Your_Current_Address_Is", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Current Homeless Status Is.
        /// </summary>
        public static string Your_Current_Homeless_Status_Is {
            get {
                return ResourceManager.GetString("Your_Current_Homeless_Status_Is", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zip Code.
        /// </summary>
        public static string Zip_Code {
            get {
                return ResourceManager.GetString("Zip_Code", resourceCulture);
            }
        }
    }
}
